apiVersion: v1
kind: Pod
metadata:
  name: nginxapp1
  labels:
    app: nginxapp1
spec:
  containers:
  - name: n1
    image: nginx:1.17.6
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80